### ISSUE TITLE
IOLoop Error

### ISSUE THREAD

**Issue by dashfuhrmann** [sebastianmenze/Tindeq-Progressor-climbing-strength-test-server#2]
Hey - i've been trying to setup your software on my windows machine. I've installed all the necesary python-libs but now I am stuck with an error during startup

Traceback (most recent call last):
  File "C:\Users\Jannik Fuhrmann\Desktop\Playground\Tindeq-Progressor-climbing-strength-test-server\tindeq_assessment\standalone.py", line 1427, in <module>
    tornado.platform.asyncio.AsyncIOMainLoop().install()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jannik Fuhrmann\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\util.py", line 276, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Jannik Fuhrmann\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 299, in initialize
    super().initialize(asyncio.get_event_loop(), **kwargs)
  File "C:\Users\Jannik Fuhrmann\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 136, in initialize
    raise RuntimeError(
RuntimeError: IOLoop <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000002592C7C1490> already associated with asyncio loop <ProactorEventLoop running=False closed=False debug=False>

Do you have any idea how I can fix this issue or what might be causing it?

Thanks in advance

**Comment by sebastianmenze** [comment]
Ah that happens sometimes and is some low level tornado ( io loop issue.
for me tho only workaround was to restart python. somehow you cant run the
tornado command more than once, but am no expert there
Cheers, Seb

Am Mo., 13. Feb. 2023 um 17:27 Uhr schrieb dashfuhrmann <
***@***.***>:

**Comment by akladnig** [comment]
I had the same issue. It turns out that tornado.platform.asyncio.AsyncIOMainLoop is deprecated so simply deleting that line of code fixed it for me. Also the latest version of Bokeh uses styles instead of style in the statements.
